### PR TITLE
adding lc_numeric to fix the issue with no facets generated

### PR DESCRIPTION
**Pull request by nlyubova**

### CODE REVIEW

**Comment by vrabaud** [comment]
can you please try out trunk ? Thx.

**Comment by nlyubova** [comment]
tested and it works perfectly !

**Comment by vrabaud** [comment]
cool ! please mention that on the mailing list

**Comment by nlyubova** [comment]
done !

**Comment by vrabaud** [comment]
yay, thx ! Just released so people should have it soonish.

**Pull request closed without merging**
